# Generated by Django 4.2.4 on 2023-09-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_jobs_is_active_alter_companyprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='file_upload',
            field=models.FileField(default='default_filename.pdf', upload_to='media/'),
        ),
    ]
