# Generated by Django 4.2.4 on 2023-09-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_students_admin_set_password_customuser_students_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'STUDENT'), (2, 'COMPANY'), (3, 'ADMIN')], default='1', null=True),
        ),
    ]
